blueprint:
  homeassistant:
    min_version: 2024.10.0
  author: trilorian
  domain: automation
  name: Ikea's Rodret, Somrig or Trådfri Remote️ Controls
  description: >
    ## Zigbee2MQTT (cf [MQTT](https://www.home-assistant.io/integrations/mqtt)
    + [Z2M addon](https://www.zigbee2mqtt.io/guide/installation/03_ha_addon.html)).

    Available controls:

    - Single click **on/off** (Rodret, Trådfri)  **1 dot/2 dots** (Somrig)

    - Double click **on/off** (Rodret, Trådfri, _Optional_)  **1 dot/2 dots** (Somrig)

    - Triple click **on/off** (Rodret, Trådfri, _Optional_)  **1 dot/2 dots** (Somrig)

    - Hold **on/off** (Rodret, Trådfri)  **1 dot/2 dots** (Somrig).
    Actions will be executed every **Hold delay**, but maximum **Max number of loops** times.
  input:
    remote_devices:
      name: Remotes
      description: >
        IKEA remote (Rodret, Somrig, Trådfri) to use.
      default: []
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: IKEA
              model: RODRET wireless dimmer/power switch
            - integration: mqtt
              manufacturer: IKEA
              model: SOMRIG shortcut button
            - integration: mqtt
              manufacturer: IKEA
              model: TRADFRI on/off switch
          multiple: true
    on_click_action:
      name: Click "on / 1 dot" action
      description: Choose action(s) to run when **on** (Rodret, Trådfri) or **1 dot** (Somrig) button is **clicked**.
      default: []
      selector:
        action: {}
    off_click_action:
      name: Click "off / 2 dots" action
      description: Choose action(s) to run when **off** (Rodret, Trådfri) or **2 dots** (Somrig) button is **clicked**.
      default: []
      selector:
        action: {}
    on_hold_action:
      name: Hold "on / 1 dot" action
      description: Choose action(s) to run when **on** (Rodret, Trådfri) or **1 dot** (Somrig) button is **held**.
      default: []
      selector:
        action: {}
    off_hold_action:
      name: Hold "off / 2 dots" action
      description: Choose action(s) to run when **off** (Rodret, Trådfri) or **2 dots** (Somrig) button is **held**.
      default: []
      selector:
        action: {}
    on_double_click_action:
      name: Double click "on / 1 dot" action
      description: >
        Choose action(s) to run when the **on** (Rodret, Trådfri) or **1 dot** (Somrig) button is **clicked twice**.

        **_NB for Rodret, Trådfri only_**: **Double click event (on)** must be exposed and **Double click delay** interval is used as a timeout.
      default: []
      selector:
        action: {}
    off_double_click_action:
      name: Double click "off / 2 dots" action
      description: >
        Choose action(s) to run when the **off** (Rodret, Trådfri) or **2 dots** (Somrig) button is **clicked twice**. 

        **_NB for Rodret, Trådfri only_**: **Double click event (off)** must be exposed and **Double click delay** interval is used as a timeout.
      default: []
      selector:
        action: {}
    on_triple_click_action:
      name: Triple click "on / 1 dot" action
      description: >
        Choose action(s) to run when the **on** (Rodret, Trådfri) or **1 dot** (Somrig) button is **clicked three times**.

        **_NB for Rodret, Trådfri only_**: **Triple click event (on)** must be exposed and **Multi click delay** interval is used as a timeout.
      default: []
      selector:
        action: {}
    off_triple_click_action:
      name: Triple click "off / 2 dots" action
      description: >
        Choose action(s) to run when the **off** (Rodret, Trådfri) or **2 dots** (Somrig) button is **clicked three times**. 

        **_NB for Rodret, Trådfri only_**: **Triple click event (off)** must be exposed and **Multi click delay** interval is used as a timeout.
      default: []
      selector:
        action: {}
    helper_section :
      name: Helpers
      icon: mdi:cog-outline
      collapsed: true
      input:
        helper_hold_delay:
          name: Hold delay
          description: Delay between the execution of the **Hold** action(s).
          default: 250
          selector:
            number:
              unit_of_measurement: milliseconds
              min: 100.0
              max: 5000.0
              step: 10.0
              mode: slider
        helper_max_loops:
          name: Max number of loops
          description: Maximum number of loops when holding down a button.
          default: 20
          selector:
            number:
              min: 1.0
              max: 1000.0
              step: 1.0
              mode: slider
    rodret_traadfri_options_section:
      name: Rodret, Trådfri options
      icon: mdi:remote
      collapsed: true
      input:
        on_double_click_exposed:
          name: Expose virtual double click "on" event
          description: >
            Choose whether or not to expose the virtual **double click** event for the **on** button. 
            Turn this on if you are providing action(s) for the **Double click action (on / 1 dot)**.
          default: false
          selector:
            boolean: {}
        off_double_click_exposed:
          name: Expose virtual double click "off" event
          description: >
            Choose whether or not to expose the virtual **double click** event for the **off** button. 
            Turn this on if you are providing an action for the **Double click action (off / 2 dots)**.
          default: false
          selector:
            boolean: {}
        on_triple_click_exposed:
          name: Expose virtual triple click "on" event
          description: >
            Choose whether or not to expose the virtual **triple click** event for the **on** button. 
            Turn this on if you are providing action(s) for the **Triple click action (on / 1 dot)**.
          default: false
          selector:
            boolean: {}
        off_triple_click_exposed:
          name: Expose virtual triple click "off" event
          description: >
            Choose whether or not to expose the virtual **triple click** event for the **off** button. 
            Turn this on if you are providing an action for the **Triple click action (off / 2 dots)**.
          default: false
          selector:
            boolean: {}
        helper_multi_click_delay:
          name: Multi click delay
          description: >
            Max delay between multiple button clickes for the
            **Double/triple click events**. Provide a value only if you are using a multi click action.
            Increase this value if you notice that the multi click action is not triggered
            properly.
          default: 250
          selector:
            number:
              unit_of_measurement: milliseconds
              min: 100.0
              max: 5000.0
              step: 10.0
              mode: slider
mode: single
max_exceeded: silent
triggers:
  # RODRET (E2201) + TRADFRI (E1743)
  - trigger: mqtt
    topic: "+/+/action"
    payload: "on"
    id: click-on-z2m-e1743-e2201
  - trigger: mqtt
    topic: "+/+/action"
    payload: "off"
    id: click-off-z2m-e1743-e2201
  - trigger: mqtt
    topic: "+/+/action"
    payload: brightness_move_up
    id: hold-on-z2m-e1743-e2201
  - trigger: mqtt
    topic: "+/+/action"
    payload: brightness_move_down
    id: hold-off-z2m-e1743-e2201
  - trigger: mqtt
    topic: "+/+/action"
    payload: brightness_stop
    id: release-z2m-e1743-e2201

  # SOMRIG (E2213)
  - trigger: mqtt
    topic: "+/+/action"
    payload: 1_short_release
    id: click-dots1-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 2_short_release
    id: click-dots2-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 1_double_click
    id: double-click-dots1-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 2_double_click
    id: double-click-dots2-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 1_long_click
    id: hold-dots1-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 2_long_click
    id: hold-dots2-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 1_long_release
    id: release-hold-dots1-z2m-e2213
  - trigger: mqtt
    topic: "+/+/action"
    payload: 2_long_release
    id: release-hold-dots2-z2m-e2213
variables:
  is_mqtt: "{{ trigger.platform == 'mqtt' }}"
  mqtt_topic: "{{ trigger.topic }}"
  on_double_click_exposed: !input on_double_click_exposed
  off_double_click_exposed: !input off_double_click_exposed
  on_triple_click_exposed: !input on_triple_click_exposed
  off_triple_click_exposed: !input off_triple_click_exposed
  remote_devices: !input remote_devices
  remote_devices_names: "{{ remote_devices | map('device_attr', 'name') | list }}"
condition:
  - condition: template
    value_template: >-
      {{ 
        (trigger.topic.split('/')[1] in remote_devices_names if is_mqtt) 
      }}
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - click-on-z2m-e1743-e2201
              - click-dots1-z2m-e2213
        sequence:
          - if:
              - condition: template
                value_template: "{{ on_double_click_exposed }}"
            then:
              - choose:
                  - conditions:
                      - condition: trigger
                        id:
                          - click-on-z2m-e1743-e2201
                    sequence:
                      - wait_for_trigger:
                          - trigger: mqtt
                            topic: "{{ mqtt_topic }}"
                            payload: "on"
                        timeout:
                          milliseconds: !input helper_multi_click_delay
                        continue_on_timeout: true
                      - if:
                          - condition: template
                            value_template: "{{ wait.trigger.idx is defined }}"
                        then: !input on_double_click_action
                        else: !input on_click_action
                default: !input on_click_action
            else: !input on_click_action
      - conditions:
          - condition: trigger
            id:
              - click-off-z2m-e1743-e2201
              - click-dots2-z2m-e2213
        sequence:
          - if:
              - condition: template
                value_template: "{{ off_double_click_exposed }}"
            then:
              - choose:
                  - conditions:
                      - condition: trigger
                        id:
                          - click-off-z2m-e1743-e2201
                    sequence:
                      - wait_for_trigger:
                          - trigger: mqtt
                            topic: "{{ mqtt_topic }}"
                            payload: "off"
                        timeout:
                          milliseconds: !input helper_multi_click_delay
                        continue_on_timeout: true
                      - if:
                          - condition: template
                            value_template: "{{ wait.trigger.idx is defined }}"
                        then: !input off_double_click_action
                        else: !input off_click_action
                default: !input off_click_action
            else: !input off_click_action
      - conditions:
          - condition: trigger
            id:
              - double-click-dots1-z2m-e2213
        sequence: !input on_double_click_action
      - conditions:
          - condition: trigger
            id:
              - double-click-dots2-z2m-e2213
        sequence: !input off_double_click_action
      #
      # Actions for up button long click
      - conditions:
          - condition: trigger
            id:
              - hold-on-z2m-e1743-e2201
              - hold-dots1-z2m-e2213
        sequence:
          - repeat:
              count: !input helper_max_loops
              sequence:
                - parallel:
                    - sequence: !input on_hold_action
                    - sequence:
                        - choose:
                            - conditions:
                                - condition: trigger
                                  id:
                                    - hold-on-z2m-e1743-e2201
                                    - hold-dots1-z2m-e2213
                              sequence:
                                - wait_for_trigger:
                                    - trigger: mqtt
                                      topic: "{{ mqtt_topic }}"
                                      payload: "brightness_stop"
                                    - trigger: mqtt
                                      topic: "{{ mqtt_topic }}"
                                      payload: "1_long_release"
                                  timeout:
                                    milliseconds: !input helper_hold_delay
                                  continue_on_timeout: true
                                - if:
                                    - condition: template
                                      value_template: "{{ wait.trigger.idx is defined }}"
                                  then:
                                    - stop: button released
      - conditions:
          - condition: trigger
            id:
              - hold-off-z2m-e1743-e2201
              - hold-dots2-z2m-e2213
        sequence:
          - repeat:
              count: !input helper_max_loops
              sequence:
                - parallel:
                    - sequence: !input off_hold_action
                    - sequence:
                        - choose:
                            - conditions:
                                - condition: trigger
                                  id:
                                    - hold-off-z2m-e1743-e2201
                                    - hold-dots2-z2m-e2213
                              sequence:
                                - wait_for_trigger:
                                    - trigger: mqtt
                                      topic: "{{ mqtt_topic }}"
                                      payload: "brightness_stop"
                                    - trigger: mqtt
                                      topic: "{{ mqtt_topic }}"
                                      payload: "2_long_release"
                                  timeout:
                                    milliseconds: !input helper_hold_delay
                                  continue_on_timeout: true
                                - if:
                                    - condition: template
                                      value_template: "{{ wait.trigger.idx is defined }}"
                                  then:
                                    - stop: button released